### ISSUE TITLE
Demo fails to load

### ISSUE THREAD

**Issue by thapapratyush** [youssef06/polymer-login-form#2]
Demo fails to load due to the following error:

Mixed Content: The page at 'https://youssef06.github.io/polymer-login-form/demo.html' was loaded over HTTPS, but requested an insecure HTML Import 'http://youssef06.github.io/polymer-login-form/login-form/login-form.html'. This request has been blocked; the content must be served over HTTPS.

**Comment by metric-space** [comment]
@thapapratyush  bub has a http link in his demo page, this was about two years ago
[here](https://github.com/youssef06/polymer-login-form/blob/gh-pages/demo.html#L6) if you have the time correct it and send it as a PR

**Comment by youssef06** [comment]
hi i updated the link to add https, can youlet me know it's working for you now?
